name: Feature request
description: Suggest an improvement to the filter
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem or idea?
      placeholder: I'd also like to …
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should it work? A new setting? A change to the heuristic?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
